---
- name: Backup FortiGate Configuration
  hosts: all  # AWX 인벤토리 설정을 따르도록 all로 변경 권장
  gather_facts: no
  connection: httpapi

  # 1. AWX에게 포티게이트 도구함을 가져오라고 명시 (에러 해결 핵심)
  collections:
    - fortinet.fortios

  tasks:
    - name: Get full configuration
      fortinet.fortios.fortios_monitor_fact:
        # Credential에서 정의했다면 변수명을 맞춰주거나 직접 입력
        access_token: "{{ fortigates_access_token }}"
        vdom: "root"
        selector: 'system_config_backup'
        params:
          scope: "global"
      register: backup_res

    - name: Ensure backup directory exists
      file:
        path: "/tmp/backups"  # 2. AWX 내부의 쓰기 가능한 임시 경로로 변경
        state: directory
      delegate_to: localhost

    - name: Save configuration to file
      copy:
        content: "{{ backup_res.meta.results if backup_res.meta.results is string else (backup_res.meta.results.out | default(backup_res.meta.raw)) }}"
        dest: "/tmp/backups/{{ inventory_hostname }}_backup.conf"
      delegate_to: localhost
      when: backup_res.meta.http_status == 200
