---
- name: Backup FortiGate Configuration
  hosts: all
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Get full configuration
      fortinet.fortios.fortios_monitor_fact:
        access_token: "{{ fortios_token }}"
        vdom: "root"      # VDOM을 사용하지 않더라도 root로 명시하는 것이 표준입니다.
        selector: 'system_config_backup'
        params:
          scope: "global" # 전체 설정을 가져오기 위한 파라미터
      register: backup_res
      # 에러 확인을 위해 잠시 주석 처리하거나 false로 두세요
      no_log: false 

    - name: Save configuration to file
      copy:
        # 응답 구조가 버전마다 다를 수 있어 더 안전한 추출 방식을 사용합니다.
        content: "{{ backup_res.meta.results.out | default(backup_res.meta.results) }}"
        dest: "/tmp/{{ inventory_hostname }}_backup.conf"
      delegate_to: localhost
      # 결과가 성공(200 OK)일 때만 저장
      when: backup_res.meta.http_status == 200
