---
- name: Backup FortiGate Configuration
  hosts: all
  gather_facts: no
  connection: httpapi
  # vars는 connection과 같은 시작 라인에 있어야 합니다.
  vars:
    ansible_port: 10443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_connect_timeout: 300
    ansible_command_timeout: 300

  tasks:
    - name: Get full configuration
      fortinet.fortios.fortios_monitor_fact:
        access_token: "{{ fortios_token }}"
        vdom: "root"
        selector: 'system_config_backup'
      register: backup_res

    - name: Save configuration to file
      copy:
        content: "{{ backup_res.meta.results.out | default(backup_res.meta.results) }}"
        dest: "/tmp/{{ inventory_hostname }}_backup.conf"
      delegate_to: localhost
      when: backup_res.meta.http_status == 200
