---
- name: Backup FortiGate Configuration
  hosts: all
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios

  tasks:
    - name: Get full configuration
      fortinet.fortios.fortios_monitor_fact:
        # 이 부분을 수정합니다! AWX Credential의 비밀번호 값을 가져오라는 뜻입니다.
        access_token: "{{ ansible_password }}" 
        vdom: "root"
        selector: 'system_config_backup'
        params:
          scope: "global"
      register: backup_res

    - name: Ensure backup directory exists
      file:
        path: "/tmp/backups"
        state: directory
      delegate_to: localhost

    - name: Save configuration to file
      copy:
        content: "{{ backup_res.meta.results if backup_res.meta.results is string else (backup_res.meta.results.out | default(backup_res.meta.raw)) }}"
        dest: "/tmp/backups/{{ inventory_hostname }}_backup.conf"
      delegate_to: localhost
      when: backup_res.meta.http_status == 200
