---
- name: Backup FortiGate Configuration
  hosts: all
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortios

  tasks:
    - name: Get full configuration
      fortinet.fortios.fortios_monitor_fact:
        # 인젝터에서 정의한 변수명을 그대로 사용합니다.
        access_token: "{{ fortios_api_token }}"
        vdom: "root"
        selector: 'system_config_backup'
        params:
          scope: "global"
      register: backup_res

    - name: Save configuration to file
      copy:
        content: "{{ backup_res.meta.results if backup_res.meta.results is string else (backup_res.meta.results.out | default(backup_res.meta.raw)) }}"
        # AWX 내부의 쓰기 가능한 경로 사용
        dest: "/tmp/{{ inventory_hostname }}_backup.conf"
      delegate_to: localhost
      when: backup_res.meta.http_status == 200
